"""
companies_house/pdf_extract.py

Extracts financial concepts from Companies House accounts filings that
are ONLY available as PDF (no iXBRL/XHTML version) — the case xbrl.py
currently gives up on and scores as NO_STRUCTURED_FINANCIAL_DATA.

Scope and assumptions:
  - This targets Companies House's own PDF filings specifically, which
    are near-universally digitally generated by accounting/filing
    software (not scanned photos) — so a real text layer is expected.
    Scanned filings fall through to ocr_extract.py instead.
  - This module ONLY extracts candidate values. It does not decide
    whether they're trustworthy, does not gate them behind approval,
    and does not merge them into any "final" signals dict. Every value
    returned here is unconfirmed until a human reviews it — hence
    `needs_manual_review` is always True on any matched concept, and
    each matched concept carries an evidence image of its source page
    for that review (see evidence.py).
  - PDF text extraction has no semantic tagging like XBRL concept
    labels — matching is done by finding a keyword phrase on a line
    and looking at the numbers that follow it. UK balance sheets
    conventionally show current-year first, prior-year second in an
    adjacent column — but multi-year comparison tables (common in
    larger/international filings) put several years' figures on one
    line, so a line with MORE THAN ONE number is flagged as
    AMBIGUOUS_MULTIPLE_VALUES rather than silently guessing which one
    is current-year.
  - Currency/locale: numbers are parsed via amount_parse.py, which
    handles £/€/$ symbols and both UK/US ("1,234.56") and EU
    ("1.234,56") separator conventions.
  - File lifecycle: this module does NOT download or delete the PDF —
    the caller (evaluate.py) owns the downloaded file's path and
    lifecycle, since the OCR fallback tier may need the same file
    afterward. Use download_accounts_pdf() to get that path.

Requires: pdfplumber, httpx
"""

import os
import tempfile
from typing import Optional

import httpx

from companies_house.client import _get, CompaniesHouseError
from companies_house.xbrl import _get_document_metadata, DOCUMENT_API_BASE
from companies_house.amount_parse import parse_amounts_in_line

# Keyword universe — same sourcing notes as xbrl.py's CONCEPT_KEYWORDS
# (FRS 102/105 model accounts, Companies House micro-entity guidance,
# common UK filing software wording). Also imported by ocr_extract.py
# so both tiers look for the same set of concepts.
CONCEPT_KEYWORDS = {
    "turnover": [
        "turnover", "total turnover", "revenue", "total revenue",
        "gross revenue", "sales", "total sales",
        "revenue from contracts with customers",
        "fee income",
    ],
    "net_assets": [
        "net assets", "net liabilities",
        "total net assets", "total net liabilities",
        "net assets/(liabilities)", "net assets (liabilities)",
        "shareholders funds", "shareholders' funds",
        "total shareholders funds", "total shareholders' funds",
        "total equity", "equity attributable to owners of the company",
        "capital and reserves", "total capital and reserves",
        "members funds", "members' funds", "total members' funds",
        "stockholders equity", "stockholders' equity",
    ],
    "current_assets": [
        "current assets", "total current assets",
    ],
    "current_liabilities": [
        "creditors: amounts falling due within one year",
        "creditors falling due within one year",
        "creditors due within one year",
        "trade and other payables falling due within one year",
        "current liabilities", "total current liabilities",
    ],
    "profit_loss": [
        "profit for the financial year", "loss for the financial year",
        "profit for the period", "loss for the period",
        "profit for the year", "loss for the year",
        "profit/(loss) for the year", "profit/(loss) for the period",
        "profit/(loss) for the financial year",
        "net profit for the year", "net loss for the year",
        "profit on ordinary activities after taxation",
        "loss on ordinary activities after taxation",
        "profit after taxation", "loss after taxation",
        "profit after tax", "loss after tax",
        "result for the year", "result for the financial year",
    ],
    "total_assets_less_current_liabilities": [
        "total assets less current liabilities",
    ],
    "creditors_due_after_one_year": [
        "creditors: amounts falling due after more than one year",
        "creditors falling due after more than one year",
        "creditors due after one year",
        "creditors due after more than one year",
    ],
    "provisions_for_liabilities": [
        "provisions for liabilities", "provisions for liability",
    ],
    "accruals_deferred_income": [
        "accruals and deferred income", "accruals",
    ],
    # Added in response to the FCA test case — large/international
    # filings frequently use "total assets" as a standalone line rather
    # than only the UK-specific subtotals above.
    "total_assets": [
        "total assets",
    ],
}

# "current assets"/"current liabilities" are substrings of both
# "non-current assets/liabilities" and "net current assets/liabilities"
# (a different subtotal) — guard against matching those by mistake.
_GUARDED_PREFIXES = {
    "current assets": ("non", "net"),
    "current liabilities": ("non", "net"),
}

_NIL_RE_WORDS = ("nil", "none")


def _matches(label: str, keyword: str) -> bool:
    idx = label.find(keyword)
    if idx == -1:
        return False
    disqualifiers = _GUARDED_PREFIXES.get(keyword)
    if not disqualifiers:
        return True
    prefix = label[:idx]
    prefix_norm = " ".join(prefix.replace("-", " ").split())
    for bad in disqualifiers:
        if prefix_norm.endswith(bad):
            return False
    return True


def _is_nil_remainder(remainder_lower: str) -> bool:
    stripped = remainder_lower.strip()
    if stripped.startswith(("-", "–", "—")):
        return True
    for word in _NIL_RE_WORDS:
        if stripped.startswith(word):
            return True
    return False


def _extract_value_after(line_lower: str, line_original: str, after_idx: int) -> dict:
    """
    Looks at the text of the line starting right after a matched
    keyword and returns one of:
      - {"state": "NIL", ...}                      — explicit dash/nil
      - {"state": "ABSENT", ...}                    — nothing usable
      - {"state": "PRESENT", "value": float, ...}   — exactly one number
      - {"state": "AMBIGUOUS_MULTIPLE_VALUES", ...} — more than one
        number on the line (e.g. a multi-year comparison table) — value
        is a best-guess (first number) but flagged untrustworthy, with
        all_values listing every candidate found.
    """
    remainder_lower = line_lower[after_idx:]

    if _is_nil_remainder(remainder_lower):
        return {
            "state": "NIL", "value": None, "currency": None,
            "all_values": None,
        }

    remainder_original = line_original[after_idx:] if len(line_original) >= after_idx else line_original
    amounts = parse_amounts_in_line(remainder_original)

    if not amounts:
        return {
            "state": "ABSENT", "value": None, "currency": None,
            "all_values": None,
        }

    if len(amounts) > 1:
        return {
            "state": "AMBIGUOUS_MULTIPLE_VALUES",
            "value": amounts[0]["value"],
            "currency": amounts[0]["currency"],
            "all_values": [a["value"] for a in amounts],
        }

    return {
        "state": "PRESENT",
        "value": amounts[0]["value"],
        "currency": amounts[0]["currency"],
        "all_values": None,
    }


def get_latest_accounts_pdf_url(company_number: str) -> Optional[str]:
    """
    Finds the most recent 'accounts' filing and returns a PDF content
    URL if a PDF resource is available for it. Call only after
    xbrl.py's get_latest_accounts_document_url() has returned None,
    i.e. prefer structured XBRL/iXBRL data whenever it exists.
    """
    history = _get(
        f"/company/{company_number}/filing-history",
        params={"category": "accounts", "items_per_page": 5},
    )
    items = history.get("items", [])
    if not items:
        return None

    latest = items[0]
    document_metadata_url = latest.get("links", {}).get("document_metadata")
    if not document_metadata_url:
        return None

    doc_id = document_metadata_url.rstrip("/").split("/")[-1]
    metadata = _get_document_metadata(doc_id)

    resources = metadata.get("resources", {})
    if "application/pdf" in resources:
        return f"{DOCUMENT_API_BASE}/document/{doc_id}/content"
    return None


def download_accounts_pdf(company_number: str) -> Optional[str]:
    """
    Resolves the latest accounts PDF for a company and downloads it to
    a local temp file, returning that file's path (or None if no PDF
    is available).

    Caller owns the returned path and is responsible for deleting it
    once ALL tiers that might need it (PDF extraction, then possibly
    OCR) have finished with it.
    """
    pdf_url = get_latest_accounts_pdf_url(company_number)
    if pdf_url is None:
        return None

    from config import COMPANIES_HOUSE_API_KEY

    resp = httpx.get(
        pdf_url,
        auth=(COMPANIES_HOUSE_API_KEY, ""),
        headers={"Accept": "application/pdf"},
        follow_redirects=True,
        timeout=30.0,
    )
    resp.raise_for_status()

    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
        tmp.write(resp.content)
        return tmp.name


def extract_candidates_from_pdf(company_number: str, pdf_path: Optional[str]) -> dict:
    """
    Returns extraction candidates for a PDF-only accounts filing:

    {
        "extraction_available": bool,
        "extraction_source": "pdf",
        "concepts": {
            "<concept_key>": {
                "state": "PRESENT" | "NIL" | "ABSENT" | "AMBIGUOUS_MULTIPLE_VALUES",
                "value": float | None,
                "currency": str | None,          # "GBP" / "EUR" / "USD" / None
                "all_values": list[float] | None,  # populated only if AMBIGUOUS
                "matched_keyword": str | None,
                "raw_line": str | None,
                "page": int | None,
                "needs_manual_review": bool,        # always True if matched
                "evidence_image_base64": str | None,
                "evidence_saved_path": str | None,
            },
            ...
        }
    }

    Takes company_number (for evidence-image storage) and pdf_path
    (from download_accounts_pdf) — does not download anything itself
    and does NOT delete pdf_path; that's the caller's responsibility.
    """
    import pdfplumber
    from companies_house.evidence import capture_from_pdfplumber_page

    empty_concepts = {
        key: {
            "state": "ABSENT", "value": None, "currency": None, "all_values": None,
            "matched_keyword": None, "raw_line": None, "page": None,
            "needs_manual_review": False,
            "evidence_image_base64": None, "evidence_saved_path": None,
        }
        for key in CONCEPT_KEYWORDS
    }

    if pdf_path is None:
        return {
            "extraction_available": False,
            "extraction_source": "pdf",
            "concepts": empty_concepts,
        }

    results = {key: dict(v) for key, v in empty_concepts.items()}

    with pdfplumber.open(pdf_path) as pdf:
        for page_num, page in enumerate(pdf.pages, start=1):
            text = page.extract_text() or ""
            for line in text.split("\n"):
                line_lower = line.lower()
                for key, keywords in CONCEPT_KEYWORDS.items():
                    if results[key]["state"] != "ABSENT":
                        continue  # first match wins
                    for kw in keywords:
                        idx = line_lower.find(kw)
                        if idx == -1 or not _matches(line_lower, kw):
                            continue
                        extracted = _extract_value_after(line_lower, line, idx + len(kw))
                        if extracted["state"] == "ABSENT":
                            continue
                        results[key] = {
                            "state": extracted["state"],
                            "value": extracted["value"],
                            "currency": extracted["currency"],
                            "all_values": extracted["all_values"],
                            "matched_keyword": kw,
                            "raw_line": line.strip(),
                            "page": page_num,
                            "needs_manual_review": True,
                            "evidence_image_base64": None,
                            "evidence_saved_path": None,
                        }
                        break

    # Capture evidence once per unique page with a match, rather than
    # re-rendering the same page for each concept that happened to land there.
    pages_with_matches = {v["page"] for v in results.values() if v["page"] is not None}
    evidence_by_page = {}
    for page_num in pages_with_matches:
        evidence = capture_from_pdfplumber_page(company_number, pdf_path, page_num)
        if evidence:
            evidence_by_page[page_num] = evidence

    for concept in results.values():
        if concept["page"] in evidence_by_page:
            ev = evidence_by_page[concept["page"]]
            concept["evidence_image_base64"] = ev["image_base64"]
            concept["evidence_saved_path"] = ev["saved_path"]

    return {
        "extraction_available": True,
        "extraction_source": "pdf",
        "concepts": results,
    }