import { AlertTriangle, CheckCircle2, Clock3, ShieldAlert } from 'lucide-react'; import type { ReactNode } from 'react';
export function Grade({grade}:{grade:string|null}){const c=grade==='A'||grade==='B'?'bg-emerald-400/15 text-emerald-300 border-emerald-400/25':grade==='C'?'bg-amber-400/15 text-amber-200 border-amber-400/25':'bg-rose-400/15 text-rose-200 border-rose-400/25';return <span className={`inline-flex min-w-7 justify-center rounded border px-2 py-1 text-xs font-bold data-num ${c}`}>{grade||'—'}</span>}
export function Severity({value}:{value:string}){const c=value==='critical'?'bg-rose-400 text-rose-950':value==='high'?'bg-orange-400 text-orange-950':value==='medium'?'bg-amber-300 text-amber-950':'bg-sky-300 text-sky-950';return <span className={`rounded px-2 py-1 text-[11px] font-bold uppercase ${c}`}>{value}</span>}
export function Empty({title,detail}:{title:string;detail:string}){return <div className="empty-compact"><CheckCircle2 className="mx-auto mb-2 h-6 w-6 text-teal-300"/><h3 className="text-sm font-semibold">{title}</h3><p className="muted mx-auto mt-1 max-w-sm text-xs">{detail}</p></div>}
export function Loading(){return <div className="space-y-4">{[1,2,3].map(i=><div className="skeleton h-24" key={i}/>)}</div>}
export function ErrorCard({message}:{message:string}){return <div className="panel rounded-xl border-rose-400/30 p-6 text-rose-200"><ShieldAlert className="mb-2"/><b>Could not load this data.</b><p className="mt-1 text-sm text-rose-200/80">{message}</p></div>}
export function IconMetric({icon,value,label,accent,tone,index}:{icon:ReactNode;value:number|string;label:string;accent:string;tone?:string;index?:number}){return <div className={`metric-card rise${index!=null?` rise-${index+1}`:''} p-5`} style={tone?{['--accent' as string]:tone}:undefined}><div className={`mb-4 inline-flex rounded-lg p-2 ${accent}`}>{icon}</div><div className="data-num text-3xl font-semibold">{value}</div><div className="muted mt-1 text-sm">{label}</div></div>}
export function Time({value}:{value:string|null|undefined}){return <span className="data-num">{value?new Date(value).toLocaleString():'Not available'}</span>}
export const attentionIcon=<AlertTriangle className="h-5 w-5"/>; export const clockIcon=<Clock3 className="h-5 w-5"/>;
