import { useEffect, useRef, useState } from 'react';
import { dashboard, evidenceUrl } from './api.js';
import { QuestionnaireButton } from './dashboardActions.jsx';
import { age, chUrl, date, intakeFields, label, present, text, tone } from './data.js';
import { Details, Empty, ErrorNotice, Future, HistoryChart, Panel, ScoreRing, SourceLink, SourceRows, Status } from './ui.jsx';
import { ReviewForm } from './actions.jsx';
import { Reports } from './pages.jsx';

const tabs = ['Overview','Corporate','Compliance','Financial evidence','Intake','Timeline','Reports'];
export function Dossier({ company: c, store, back, openAlert, report, notice }) {
  const [tab,setTab] = useState('Overview'), [busy,setBusy] = useState(false), [error,setError] = useState(''), [form,setForm] = useState(null);
  const [currentReport,setCurrentReport] = useState(null), [reportError,setReportError] = useState(''), [reportBusy,setReportBusy] = useState(false), [reportVersion,setReportVersion] = useState(0);
  const signals = c.signals, latest = c.detail?.latest || {}, risk = c.risk || {}, decisions = c.detail?.review_decisions || [];
  const snapshotId = latest.snapshot_id;
  useEffect(() => {
    if (!['Timeline','Compliance'].includes(tab)) return;
    let active = true; setReportBusy(true);setReportError('');
    dashboard.report(c.vendor_id).then(r=>{if(active)setCurrentReport(r);}).catch(e=>{if(active)setReportError(e.message);}).finally(()=>{if(active)setReportBusy(false);});
    return () => { active = false; };
  }, [tab,c.vendor_id,snapshotId,reportVersion]);
  const refresh = async () => {
    if(busy)return;setBusy(true);setError('');
    try { const r=await dashboard.refresh(c.vendor_id); if(r.status==='refreshed'){notice('Company assessment refreshed.');await store.reload();}else{setError(r.message || r.detail || 'Refresh returned '+(r.status||'an unrecognised state')+'. Reload saved data before retrying.');} }catch(e){setError(e.message);}finally{setBusy(false);}
  };
  const saved = () => {setForm(null);notice('Review saved in the backend.');setReportVersion(v=>v+1);store.reload();};
  return <><div className="backline"><button onClick={back}>‹ Companies</button><span> / {c.name}</span></div>
    <div className="dossier-head"><div className="company-hero"><span className="hero-avatar">{c.name?.[0]||'C'}</span><div><p className="eyebrow">MONITORED COMPANY · {c.company_number}</p><h1>{c.name}</h1><div><Status value={signals.company_status}/><Status value={c.criticality}>{c.criticality} criticality</Status><Status color="blue">Checked {age(c.last_checked)}</Status></div></div></div><div className="hero-actions"><button className="filter" onClick={report}>⇩ Export pack</button><button className="primary" disabled={busy} onClick={refresh}>{busy?'↻ Checking company…':'↻ Refresh'}</button></div></div>
    <ErrorNotice error={error}/>{Object.entries(c.errors).map(([key,value])=><ErrorNotice key={key} error={label(key)+': '+value} retry={store.reload}/>)}
    {!c.detail && !c.errors.detail && <p className="panel-note">Loading saved company detail…</p>}
    <div className="decision-bar"><div><span>Decision status</span><b>{risk.overall_status==='BLOCKED'?'Blocked by status':label(decisions[0]?.decision || risk.overall_status || 'not_assessed')}</b><small>{risk.assessment_label || 'Awaiting assessment data'}</small></div><div><span>Risk score</span><b>{c.latest_score ?? '—'} <em>/ 100</em></b><small className={c.delta !== null && c.delta>=0?'up':''}>{c.delta===null?'Trend not available':(c.delta>0?'+':'')+c.delta+' points since previous assessment'}</small></div><div><span>Data confidence</span><b>{label(risk.data_confidence || c.data_confidence)}</b><small>{risk.is_provisional?'Assessment is provisional':'Refer to source coverage'}</small></div><div><span>Open alerts</span><b>{store.errors.alerts?'—':c.openAlerts.length}</b><small>{c.openAlerts.length?'Earliest SLA: '+date(c.openAlerts.map(a=>a.sla_due_at).sort()[0]):'No open alerts returned'}</small></div></div>
    <div className="tabs" role="tablist" aria-label="Company dossier">{tabs.map(t=><button role="tab" aria-selected={tab===t} key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
    <div role="tabpanel" aria-label={tab}>
      {tab==='Overview' && <div className="dossier-grid"><Panel title="Decision context" eyebrow="RISK OVERVIEW" action={<ScoreRing score={c.latest_score} grade={c.latest_grade}/>} className="risk-card"><p className="risk-copy">{risk.assessment_label || 'No risk assessment available.'} · {risk.is_provisional?'Coverage gaps or review requirements limit this assessment.':'Scores describe the available assessed signals.'}</p><div className="dimensions">{['CORPORATE','FINANCIAL','OWNERSHIP','COMPLIANCE','REPUTATION','CYBER'].map(name=>{const d=risk.dimensions?.[name] || risk.dimensions?.[name.toLowerCase()];return <div key={name}><span>{label(name)}</span><b className={tone(d?.state)}>{d?.score ?? '—'}</b><small>{label(d?.state)}</small><p>{d?.summary || 'No assessment returned'}</p></div>;})}</div></Panel>
      <Panel title="Action queue" eyebrow="OPEN ALERTS" className="alert-card">{c.openAlerts.length?c.openAlerts.map(a=><button className="alert-compact" key={a.alert_id} onClick={()=>openAlert(a.alert_id)}><span className={'severity-dot '+a.severity}/><div><Status value={a.severity}/><b>{a.title}</b><p>{a.reason}</p></div><i>›</i></button>):<Empty title="No open alerts returned"/>}</Panel>
      <Panel title="Last five assessments" eyebrow="SCORE HISTORY" className="trend-card"><HistoryChart history={c.history}/></Panel>
      <Panel title={decisions.length?label(decisions[0].decision):'No final decision recorded'} eyebrow="REVIEWER DECISION" className="review-card"><p>{decisions.length?'Recorded by '+decisions[0].reviewer+' · '+date(decisions[0].created_at):'Review the dossier and outstanding evidence, then record your decision.'}</p>{decisions[0]?.note && <p>{decisions[0].note}</p>}<div><QuestionnaireButton vendor={c} label="Request information"/><button className="primary" disabled={!c.detail} onClick={()=>setForm({kind:'company'})}>Record decision</button></div></Panel>
      <Panel title="Score factors" eyebrow={'SCORING VERSION '+(latest.scoring_version||'UNKNOWN')} className="full-span"><p className="panel-note">Financial values inferred from OCR are not displayed here.</p>{Object.entries(latest.categories||{}).map(([key,category])=><details className="factor-category" key={key}><summary>{label(key)} <span>{category.unscored?'Unassessed':text(category.score)+' / 100'} · Weight {Math.round((category.weight||0)*100)}%</span></summary>{category.factors?.length?category.factors.map((f,i)=><div className="factor" key={f.code+i}><Status value={f.severity}/><div><b>{label(f.code)}</b><p>{f.description}</p></div><small>{f.points ?? '—'} points</small></div>):<p className="panel-note">No scoring factors returned for this category.</p>}</details>)}</Panel>
      <Panel title="Coverage & review" eyebrow="DATA QUALITY" className="full-span"><SourceRows rows={c.coverage?.data_freshness}/><p className="panel-note">{c.coverage?.financial_review?.label || 'Financial review status unavailable'}</p><Details rows={[[ 'Data issues',(latest.data_quality?.issues || []).map(label).join(', ') || 'None returned'],['Human review recommended',latest.recommend_manual_review],['Source check timestamp',date(latest.data_quality?.checked_at)]]}/></Panel></div>}
      {tab==='Corporate' && <Corporate company={c}/>}
      {tab==='Compliance' && <Compliance company={c} report={currentReport} loading={reportBusy} error={reportError} review={event=>setForm({kind:'event',event})}/>}
      {tab==='Financial evidence' && <Evidence key={snapshotId || c.vendor_id} company={c} review={()=>setForm({kind:'financial',snapshotId})}/>}
      {tab==='Intake' && <IntakeDetail company={c}/>} 
      {tab==='Timeline' && <><ErrorNotice error={reportError}/>{reportBusy && <p className="panel-note">Loading material events…</p>}<Timeline company={c} report={currentReport} review={event=>setForm({kind:'event',event})}/></>}
      {tab==='Reports' && <Reports companies={[c]} initialId={c.vendor_id} notice={notice}/>}
    </div>
    {form?.kind==='company' && <ReviewForm title="Record company decision" kind="company" choices={['pending_review','approved','approved_with_conditions','needs_information','rejected'].map(x=>[x,label(x)])} close={()=>setForm(null)} submit={f=>dashboard.decision(c.vendor_id,{decision:f.choice,reviewer:f.actor,note:f.note,next_review_at:f.nextReview})} onSaved={saved}/>}
    {form?.kind==='financial' && <ReviewForm title="Review filing evidence" choices={['pending','reviewed','reprocess_required','not_required','unavailable'].map(x=>[x,label(x)])} initial={c.coverage?.financial_review?.status || 'pending'} extra={<p className="panel-note">This records a review against the latest backend snapshot. It does not validate or edit OCR figures. You opened this review for snapshot #{form.snapshotId}.</p>} close={()=>setForm(null)} submit={async f=>{const current=await dashboard.coverage(c.vendor_id);if(current.snapshot_id!==form.snapshotId)throw new Error('A newer assessment is available. Close this form and reload before reviewing.');return dashboard.financialReview(c.vendor_id,{status:f.choice,reviewer:f.actor,note:f.note});}} onSaved={saved}/>}
    {form?.kind==='event' && <ReviewForm title={'Review event #'+form.event.event_id} choices={['needs_information','false_positive','confirmed_match','dismissed'].map(x=>[x,label(x)])} extra={<p>{form.event.title}</p>} close={()=>setForm(null)} submit={f=>dashboard.eventReview(form.event.event_id,{decision:f.choice,reviewer:f.actor,note:f.note})} onSaved={saved}/>}
  </>;
}
function Corporate({ company:c }) {
  const s=c.signals, address=s.registered_office_address || {};
  return <div className="dossier-grid"><Panel title="Companies House profile" action={<SourceLink url={chUrl(c.company_number)}/>}><Details rows={[[ 'Company number',c.company_number],['Status',s.company_status],['Registered address',Object.values(address).filter(Boolean).join(', ') || null],['Accounts overdue',s.accounts_overdue],['Confirmation statement overdue',s.confirmation_statement_overdue],['Repeated late filing notices',s.repeated_late_filing_notices],['Late filing notice count',s.late_filing_notice_count]]}/></Panel>
    <Panel title="Directors & officers" action={<SourceLink url={chUrl(c.company_number,'/officers')}/>}><Details rows={[[ 'Active officer count',s.active_officer_count],['Recent resignations',s.recent_resignations],['Disqualified officer flag',s.has_disqualified_officer],['Disqualified officer names',s.disqualified_officer_names?.join(', ') || null]]}/>{s.active_officers?.length?s.active_officers.map((p,i)=><div className="record-block" key={i}><b>{p.name}</b><Details rows={Object.entries(p).filter(([k])=>k!=='name').map(([k,v])=>[label(k),v])}/></div>):<Empty title="No officer records returned"/>}</Panel>
    <Panel title="Persons with significant control" action={<SourceLink url={chUrl(c.company_number,'/persons-with-significant-control')}/>}><Details rows={[[ 'PSC data available',s.psc_data_available],['Active PSC count',s.active_psc_count],['PSC changed recently',s.psc_changed_recently],['PSC details unclear',s.psc_details_unclear]]}/>{s.active_pscs?.length?s.active_pscs.map((p,i)=><div className="record-block" key={i}><b>{p.name}</b><Details rows={Object.entries(p).filter(([k])=>k!=='name').map(([k,v])=>[label(k),v])}/></div>):<Empty title="No PSC records returned"/>}</Panel>
    <Panel title="Charges & insolvency" action={<SourceLink url={chUrl(c.company_number,'/charges')}/>}><Details rows={[[ 'Total charges',s.charge_count],['Outstanding charges',s.outstanding_charge_count],['Floating charge',s.has_floating_charge],['Active insolvency case',s.has_active_insolvency_case],['Active insolvency case count',s.active_insolvency_case_count],['Insolvency history',s.has_insolvency_history]]}/><div className="panel-note"><SourceLink url={chUrl(c.company_number,'/filing-history')}>Filing history ↗</SourceLink></div></Panel></div>;
}
function Compliance({ company:c, report, loading, error, review }) {
  const s=c.signals, events=(report?.material_events||[]).filter(e=>e.category==='COMPLIANCE');
  return <div className="dossier-grid"><Panel title={label(s.sanctions_match_state || 'screening_unavailable')} eyebrow="UK SANCTIONS SCREENING" className="compliance-status" action={<Status value={s.sanctions_review_required?'review_required':s.sanctions_screening_available?'assessed':'unavailable'}/>}><p>Possible name matches require human review. A screening similarity score is not the probability that two entities are the same.</p><Details rows={[[ 'Screening available',s.sanctions_screening_available],['Confirmed match flag',s.sanctions_match],['Candidate name',s.sanctions_candidate_name],['Candidate alias',s.sanctions_candidate_alias],['Candidate ID',s.sanctions_candidate_unique_id],['Match name',s.sanctions_match_name],['Match ID',s.sanctions_match_unique_id],['Name similarity score',s.sanctions_match_score],['Matching fields',s.sanctions_matching_fields?.join(', ')],['Review required',s.sanctions_review_required],['Screening checked',date(s.sanctions_checked_at)],['List fetched',date(s.sanctions_list_fetched_at)],['List version',s.sanctions_list_version],['Screening error',s.sanctions_screening_error]]}/><div className="evidence-box"><b>Screening source</b><SourceLink url={s.sanctions_source_url}/></div></Panel>
    <Panel title="People screening"><Details rows={[[ 'Director / PSC match state',s.director_or_psc_sanctions_match_state],['Confirmed match flag',s.director_or_psc_sanctions_match],['Review required',s.director_or_psc_sanctions_review_required]]}/>{(s.people_sanctions_matches||[]).map((p,i)=><div className="record-block" key={i}><Details rows={Object.entries(p).map(([k,v])=>[label(k),v])}/></div>)}</Panel><Panel title="Source coverage"><SourceRows rows={c.coverage?.data_freshness}/><p className="panel-note">PEP, debarment, regulatory enforcement, Gazette/news and cyber provider coverage is not assumed from a blank result.</p></Panel>
    <Panel title="Compliance event reviews" className="full-span"><ErrorNotice error={error}/>{loading?<p className="panel-note">Loading events…</p>:events.length?events.map(e=><EventCard event={e} key={e.event_id} review={review}/>):<Empty title="No compliance events returned"/>}</Panel>
  </div>;
}
function Evidence({ company:c, review }) {
  const pages=[...(c.detail?.financial_evidence||[])].sort((a,b)=>a.page-b.page);
  const [selected,setSelected]=useState(pages[0]?.evidence_id), [continuous,setContinuous]=useState(true), [zoom,setZoom]=useState(100);
  const viewport=useRef(null);
  const active=pages.find(p=>p.evidence_id===selected)||pages[0], index=pages.findIndex(p=>p.evidence_id===active?.evidence_id);
  const select=p=>{if(!p)return;setSelected(p.evidence_id);if(continuous)document.getElementById('evidence-page-'+p.evidence_id)?.scrollIntoView({behavior:'smooth',block:'nearest'});};
  return <><div className="evidence-note">Original filing images only. OCR-extracted financial figures are not displayed.</div><div className="evidence-layout"><Panel title={pages.length?'Accounts filing · page '+active?.page+' · '+pages.length+' captured pages':'Accounts filing evidence'} eyebrow="FILING EVIDENCE" className="evidence-view" action={<div className="evidence-tools"><button className="filter" aria-label="Previous evidence page" disabled={index<=0} onClick={()=>select(pages[index-1])}>←</button><button className="filter" aria-label="Next evidence page" disabled={index>=pages.length-1} onClick={()=>select(pages[index+1])}>→</button></div>}>
    <div className="evidence-controls"><label><input type="checkbox" checked={continuous} onChange={e=>setContinuous(e.target.checked)}/> Scroll all pages</label><label>Zoom <select value={zoom} onChange={e=>setZoom(Number(e.target.value))}>{[75,100,125,150,200].map(n=><option value={n} key={n}>{n}%</option>)}</select></label><button className="filter" disabled={!c.detail} onClick={review}>Record financial review</button></div>
    <div className="evidence-scroll" ref={viewport}>{pages.length?(continuous?pages:[active]).map(p=><figure key={p.evidence_id} id={'evidence-page-'+p.evidence_id} style={{width:zoom+'%'}}><figcaption>Page {p.page} · Captured {date(p.captured_at)}</figcaption><EvidenceImage page={p}/></figure>):<Empty title="No filing images available">The latest assessment has not returned any captured pages. Try refreshing the company, then check source availability.</Empty>}</div>
    <div className="evidence-foot"><Status value={c.coverage?.financial_review?.status}>{c.coverage?.financial_review?.label||'Review status unavailable'}</Status><span>{c.coverage?.financial_review?.reviewer && 'Reviewed by '+c.coverage.financial_review.reviewer}</span><SourceLink url={active?.companies_house_filing_history_url || chUrl(c.company_number,'/filing-history')}>Open source ↗</SourceLink></div>
    {c.coverage?.financial_review?.note && <p className="panel-note">{c.coverage.financial_review.note}</p>}
    </Panel><aside className="thumb-rail" aria-label="Evidence page navigation"><p>Pages</p>{pages.map(p=><button aria-label={'Go to page '+p.page} key={p.evidence_id} className={active?.evidence_id===p.evidence_id?'current':''} onClick={()=>select(p)}>{p.page}</button>)}</aside></div></>;
}
function EvidenceImage({ page }) {
  const [failed,setFailed]=useState(false), [attempt,setAttempt]=useState(0);
  const url=evidenceUrl(page.image_url);
  if(!url)return <ErrorNotice error="Evidence image URL was not recognised."/>;
  return failed?<Empty title={'Page '+page.page+' is unavailable'} action={<button className="filter" onClick={()=>{setFailed(false);setAttempt(n=>n+1);}}>Retry image</button>}>The file may be missing, or your session may have expired.</Empty>:<img key={attempt} src={url+(attempt?'?retry='+attempt:'')} alt={'Companies House filing, page '+page.page} loading="lazy" onError={()=>setFailed(true)}/>;
}
function IntakeDetail({ company:c }) {
  const intake=c.detail?.intake;
  return <section className="intake-layout"><div className="panel intake-summary"><span className="eyebrow">DUE-DILIGENCE INTAKE</span><h2>{c.intakeState}</h2><p>{c.intakeState==='Not supplied'?'No additional onboarding information was supplied. An internal reviewer should obtain it from the company.':'Review stored answers alongside the source evidence. Field completeness is not approval.'}</p><p>Each questionnaire has a one-time, 30-day link. The response is recorded against this company.</p><div><QuestionnaireButton className="primary" vendor={c}/><Future reason="Intake editing endpoint pending">Record internal assessment</Future></div></div><div className="panel intake-list">{intakeFields.map(([key,name])=><div className="intake-row" key={key}><div><b>{name}</b><small>{key==='supplier_criticality'?'Internal classification':'Stored intake field · provenance unavailable'}</small></div><span>{text(intake?.[key])}</span><Status color={present(intake?.[key])?'good':'watch'}>{present(intake?.[key])?'Supplied':'Missing'}</Status></div>)}<div className="intake-row"><div><b>Insurance evidence</b><small>Document-request connection pending</small></div><span>Not connected</span><Status value="unknown"/></div></div></section>;
}
function EventCard({ event:e, review }) { return <div className="record-block"><div className="event-heading"><b>{e.title}</b><Status value={e.severity}/></div><p>{e.description}</p><small>{date(e.detected_at)} · {label(e.source)} · Confidence {label(e.confidence)}</small>{e.caution && <p className="evidence-note">{e.caution}</p>}<div className="event-actions"><SourceLink url={e.source_url}/><button className="filter" onClick={()=>review(e)}>Review event</button></div>{e.review && <p className="muted">Latest review: {label(e.review.decision)} · {e.review.reviewer} · {date(e.review.created_at)} · {e.review.note}</p>}<details><summary>Evidence references</summary>{(e.evidence||[]).map((v,i)=><div key={i}><Details rows={Object.entries(v).filter(([k])=>k!=='source_url').map(([k,value])=>[label(k),value])}/><SourceLink url={v.source_url}/></div>)}</details></div>; }
function Timeline({ company:c, report, review }) {
  return <><Panel title="Material company events" eyebrow="SOURCE EVENTS">{report?.material_events?.length?report.material_events.map(e=><EventCard key={e.event_id} event={e} review={review}/>):<Empty title="No source events returned"/>}</Panel><Panel title="Audit timeline" eyebrow="RECORDED ACTIVITY" className="timeline">{c.detail?.audit_events?.length?c.detail.audit_events.map(e=><div className="timeline-row" key={e.id}><i/><div><small>{date(e.created_at)} · {e.actor||'No actor recorded'}</small><b>{label(e.action)}</b><p>{text(e.details)}</p>{e.alert_id && <small>Alert #{e.alert_id}</small>}</div></div>):<Empty title="No audit entries returned"/>}</Panel><Panel title="Reviewer decisions" eyebrow="DECISION HISTORY">{(c.detail?.review_decisions||[]).map(d=><div className="record-block" key={d.decision_id}><b>{label(d.decision)}</b><p>{d.note}</p><small>{d.reviewer} · {date(d.created_at)} · Next review: {date(d.next_review_at)}</small></div>)}</Panel></>;
}
