import { createContext, useContext, useState } from 'react';
import { dashboard } from './api.js';
import { BulkImportButton, EmailReportButton } from './dashboardActions.jsx';
import { age, date, download, exportCsv, intakeFields, isOpen, label, present, severityRank, sourceRows, text, timestamp } from './data.js';
import { Details, Empty, ErrorNotice, Future, HistoryChart, Metric, Modal, PageTitle, Panel, ScoreRing, SourceLink, SourceRows, Status } from './ui.jsx';

export const ReportSession = createContext(null);

export function Overview({ store, choose, go, openAlert }) {
  const {companies,alerts} = store;
  const open = alerts.filter(isOpen).sort((a,b)=>severityRank(b.severity)-severityRank(a.severity));
  const sources = sourceRows(companies), good = sources.filter(s=>s.state==='healthy').length;
  const review = companies.filter(c=>c.recommend_manual_review || ['BLOCKED','REVIEW_REQUIRED'].includes(c.risk?.overall_status));
  const [trendId,setTrendId] = useState('');
  const trendCompany = companies.find(c=>String(c.vendor_id)===trendId) || companies[0];
  return <><PageTitle eyebrow={new Date().toLocaleDateString('en-GB',{timeZone:'Europe/London',weekday:'long',day:'numeric',month:'long'})} title="Your monitoring workspace." description="Here is what needs attention across your monitored companies."><Future className="primary" reason="Company onboarding connection pending">+ Monitor company</Future></PageTitle>
    <div className="metric-grid"><Metric label="Monitored companies" value={companies.length} sub="Active monitoring inventory" icon="▦" color="blue"/><Metric label="Needs review" value={store.enriching ? '…' : review.length} sub="Review flags from available assessments" icon="◉" color="amber"/><Metric label="Open alerts" value={store.errors.alerts ? '—' : open.length} sub={open.filter(a=>['high','critical'].includes(a.severity)).length + ' high / critical priority'} icon="!" color="coral"/><Metric label="Data freshness" value={sources.length ? Math.round(good/sources.length*100)+'%' : '—'} sub={good + '/' + sources.length + ' reported source checks healthy'} icon="↻" color="teal"/></div>
    <div className="layout-two overview-main"><Panel title="Review next" eyebrow="PRIORITY QUEUE" action={<button className="text-button" onClick={()=>go('Alerts')}>View all →</button>}>{open.length ? open.slice(0,4).map(a=><button className="queue-item" key={a.alert_id} onClick={()=>openAlert(a.alert_id)}><span className={'severity-dot '+a.severity}/><div><b>{companies.find(c=>c.vendor_id===a.vendor_id)?.name || 'Company #'+a.vendor_id}</b><p>{a.title}</p></div><span className="queue-meta"><Status value={a.severity}/><small>Due {date(a.sla_due_at)}</small></span><i>›</i></button>) : <Empty title={store.errors.alerts ? 'Alert data unavailable' : 'No open alerts'}>Review company coverage before making a decision.</Empty>}</Panel>
    <Panel title="Risk trend" eyebrow="PORTFOLIO HEALTH" className="chart-panel" action={<select aria-label="Trend company" value={trendCompany?.vendor_id || ''} onChange={e=>setTrendId(e.target.value)}><option value="" disabled>Select company</option>{companies.map(c=><option key={c.vendor_id} value={c.vendor_id}>{c.name}</option>)}</select>}><div className="chart-legend"><span>Selected company · last five assessments</span><b>{trendCompany?.latest_score ?? '—'}</b></div><HistoryChart history={trendCompany?.history}/><p className="panel-note">Portfolio-wide history is pending a backend endpoint. Individual score histories are available now.</p></Panel></div>
    <div className="layout-two lower"><Panel title="Watchlist snapshot" eyebrow="MONITORED COMPANIES" action={<button className="text-button" onClick={()=>go('Companies')}>See all →</button>}>{companies.length ? companies.slice(0,5).map(c=><button className="mini-company" key={c.vendor_id} onClick={()=>choose(c)}><span className="company-avatar">{c.name?.[0] || 'C'}</span><div><b>{c.name}</b><small>{c.company_number} · {c.criticality} criticality</small></div><HistoryChart small history={c.history}/><ScoreRing size="small" score={c.latest_score} grade={c.latest_grade}/><i>›</i></button>) : <Empty title="Your portfolio is empty">Companies added through the current onboarding workflow will appear here automatically.</Empty>}</Panel>
    <Panel title="Monitoring coverage" eyebrow="SOURCE HEALTH" action={<button className="text-button" onClick={()=>go('Operations')}>All sources →</button>}><SourceRows rows={sources.slice(0,5)}/><div className="source-row"><span className="source-icon neutral">◌</span><div><b>External intelligence</b><small>Provider connection pending</small></div><Status value="unavailable"/></div><div className="source-row"><span className="source-icon watch">▱</span><div><b>Financial evidence</b><small>{companies.filter(c=>c.coverage?.financial_review?.status==='pending').length} reported reviews pending</small></div></div></Panel></div>
  </>;
}
export function Companies({ companies, search, setSearch, choose, enriching }) {
  const [filter,setFilter] = useState('All'), [criticality,setCriticality] = useState('All'), [sort,setSort] = useState('name'), [showFilters,setShowFilters] = useState(false);
  const items = companies.filter(c=>(c.name||'').toLowerCase().includes(search.toLowerCase()) || c.company_number.includes(search)).filter(c=>criticality==='All' || c.criticality.toLowerCase()===criticality.toLowerCase()).filter(c=>filter==='All' || (filter==='Needs review' && (c.recommend_manual_review || c.risk?.overall_status==='REVIEW_REQUIRED')) || (filter==='Blocked' && c.risk?.overall_status==='BLOCKED') || (filter==='Intake incomplete' && ['Intake incomplete','Not supplied'].includes(c.intakeState))).sort((a,b)=>sort==='score' ? (a.latest_score ?? 101)-(b.latest_score ?? 101) : (a.name||'').localeCompare(b.name||''));
  return <><PageTitle eyebrow="PORTFOLIO" title="Monitored companies" description="Search, investigate, and prioritise your company risk inventory."><BulkImportButton/></PageTitle><section className="panel table-panel"><div className="table-tools"><div className="search"><span>⌕</span><input aria-label="Search companies" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search company name or number"/></div><button className="filter" aria-expanded={showFilters} onClick={()=>setShowFilters(!showFilters)}>☷ Filters</button><button className="filter" onClick={()=>exportCsv('monitored-companies.csv',[['Company','Company number','Criticality','Score','Grade','Confidence','Intake','Open alerts','Last checked'],...items.map(c=>[c.name,c.company_number,c.criticality,c.latest_score,c.latest_grade,c.data_confidence,c.intakeState,c.openAlerts.length,c.last_checked])])}>⇩ Export</button></div>
    {showFilters && <div className="filter-controls"><label>Criticality<select value={criticality} onChange={e=>setCriticality(e.target.value)}>{['All','Critical','High','Medium','Low','Unknown'].map(s=><option key={s}>{s}</option>)}</select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Company name</option><option value="score">Lowest score first</option></select></label></div>}
    <div className="filter-pills">{['All','Needs review','Blocked','Intake incomplete'].map(f=><button key={f} className={'filter '+(filter===f?'selected':'')} onClick={()=>setFilter(f)}>{f}{f==='All'?' '+companies.length:''}</button>)}{enriching && <small className="muted">Loading company details…</small>}</div>
    <div className="table-scroll"><div className="company-table"><div className="table-head"><span>Company</span><span>Criticality</span><span>Risk</span><span>Trend</span><span>Intake</span><span>Alerts</span><span>Last checked</span></div>{items.map(c=><button className="table-row" key={c.vendor_id} onClick={()=>choose(c)}><div className="company-cell"><span className="company-avatar">{c.name?.[0]||'C'}</span><span><b>{c.name}</b><small>{c.company_number} · {label(c.signals.company_status)}</small></span></div><span><Status value={c.criticality}/></span><span className="risk-cell"><ScoreRing score={c.latest_score} grade={c.latest_grade} size="tiny"/><b>{c.latest_grade || '—'} / {c.latest_score ?? '—'}<small>{c.risk?.is_provisional ? 'Provisional' : label(c.data_confidence)+' confidence'}</small></b></span><span><HistoryChart small history={c.history}/></span><span><Status color={c.intakeState==='Fields supplied'?'good':'watch'}>{c.intakeState}</Status></span><span className={c.openAlerts.length?'alert-count':'muted'}>{c.openAlerts.length || '—'}</span><small>{age(c.last_checked)}</small></button>)}</div></div>
    {!items.length && <Empty title={companies.length?'No matching companies':'No companies monitored'}>{companies.length?'Try another search or filter.':'Onboard a company through your existing workflow to begin.'}</Empty>}</section></>;
}
export function Alerts({ alerts, companies, openAlert }) {
  const [search,setSearch] = useState(''), [status,setStatus] = useState('active'), [severity,setSeverity] = useState('All');
  const names = Object.fromEntries(companies.map(c=>[c.vendor_id,c.name]));
  const rows = alerts.filter(a=>(status==='all' || (status==='active'?isOpen(a):a.status===status)) && (severity==='All' || a.severity===severity) && (a.title+' '+a.reason+' '+names[a.vendor_id]).toLowerCase().includes(search.toLowerCase()));
  return <><PageTitle eyebrow="TRIAGE INBOX" title="Alerts" description="Assign, acknowledge, and resolve evidence-backed monitoring events."><button className="filter" onClick={()=>exportCsv('alerts.csv',[['Alert ID','Company','Severity','Status','Reason','Owner','SLA due'],...rows.map(a=>[a.alert_id,names[a.vendor_id],a.severity,a.status,a.reason,a.assigned_to,a.sla_due_at])])}>⇩ Export list</button></PageTitle><section className="panel table-panel"><div className="table-tools"><div className="search"><span>⌕</span><input aria-label="Search alerts" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search alerts"/></div><select aria-label="Alert status" value={status} onChange={e=>setStatus(e.target.value)}>{['active','all','open','acknowledged','escalated','resolved','false_positive','resolve'].map(s=><option key={s} value={s}>{s==='resolve'?'Legacy resolve status':label(s)}</option>)}</select><select aria-label="Alert severity" value={severity} onChange={e=>setSeverity(e.target.value)}>{['All','critical','high','medium','low'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></div>
    {rows.map(a=><button className="alert-row" key={a.alert_id} onClick={()=>openAlert(a.alert_id)}><Status value={a.severity}/><div><b>{names[a.vendor_id] || 'Company #'+a.vendor_id}</b><p>{a.title}</p></div><span>{a.assigned_to || 'Unassigned'}</span><b className="sla">{isOpen(a) && timestamp(a.sla_due_at)?.getTime()<Date.now()?'Overdue · ':''}{date(a.sla_due_at)}</b><Status value={a.status}/><i>›</i></button>)}
    {!rows.length && <Empty title="No alerts in this view">Adjust the status or search to see other records.</Empty>}</section></>;
}
export function Intake({ companies, choose }) {
  const rows = companies.filter(c=>c.intakeState!=='Fields supplied');
  return <><PageTitle eyebrow="ONBOARDING CONTROL" title="Intake & requests" description="Track missing company information without blocking basic monitoring."><BulkImportButton/></PageTitle>
    <div className="metric-grid"><Metric label="Intake incomplete" value={companies.filter(c=>['Intake incomplete','Not supplied'].includes(c.intakeState)).length} sub="Based on supplied assessment fields" icon="▤" color="amber"/><Metric label="Questionnaires sent" value="—" sub="Request tracking not connected" icon="↗" color="blue"/><Metric label="Evidence requested" value="—" sub="Request tracking not connected" icon="⌁" color="teal"/><Metric label="Fields supplied" value={companies.filter(c=>c.intakeState==='Fields supplied').length} sub="Completeness does not mean approval" icon="✓" color="coral"/></div>
    <Panel title="Companies requiring information" eyebrow="REQUEST QUEUE" action={<Future reason="Questionnaire templates pending">Manage templates →</Future>}>{rows.map(c=><div className="request-row" key={c.vendor_id}><span className="company-avatar">{c.name?.[0]||'C'}</span><div><button className="text-button" onClick={()=>choose(c)}>{c.name}</button><small>{c.criticality} criticality · {c.intakeState}</small></div><span className="missing-list">{c.detail ? intakeFields.filter(([key])=>!present(c.detail.intake?.[key])).length+' fields not supplied' : 'Details unavailable'}</span><Status color="watch">{c.intakeState}</Status><Future reason="Questionnaire delivery pending">Send request</Future></div>)}{!rows.length && <Empty title="No incomplete intake records">Stored answers still require review.</Empty>}</Panel></>;
}
export function Reports({ companies, initialId, notice }) {
  const [id,setId] = useState(initialId ? String(initialId) : ''), [preview,setPreview] = useState(null), [error,setError] = useState(''), [busy,setBusy] = useState(false);
  const [generator,setGenerator] = useState(false), [actor,setActor] = useState('');
  const [generated,setGenerated] = useContext(ReportSession);
  const target = id || String(companies[0]?.vendor_id || '');
  const load = async () => { if(!target || busy)return; setError(''); setBusy(true);try{setPreview({payload:await dashboard.report(target),current:true});}catch(e){setError(e.message);}finally{setBusy(false);} };
  const generate = async e => {e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await dashboard.createReport(target,actor.trim());setGenerated(g=>[r,...g]);setPreview(r);setGenerator(false);notice('Immutable report snapshot saved in the backend.');}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <><PageTitle eyebrow="AUDIT-READY OUTPUT" title="Reports" description="Review evidence, generate immutable company snapshots, and export structured reports."><button className="primary" disabled={!target || busy} onClick={()=>setGenerator(true)}>+ Generate report</button></PageTitle><ErrorNotice error={error}/>
    <div className="report-selector"><label>Company<select value={target} onChange={e=>setId(e.target.value)} disabled={busy}>{!companies.length && <option value="">No companies</option>}{companies.map(c=><option key={c.vendor_id} value={c.vendor_id}>{c.name}</option>)}</select></label></div>
    <section className="panel report-panel">{[
      ['Daily operational digest','Portfolio changes, alert queue, source health',false],
      ['Company audit pack','Full structured evidence report for the selected company',true],
      ['Monthly portfolio review','Trends, SLA performance, review coverage',false],
    ].map(([name,body,ready])=><div className="report-row" key={name}><span className="report-icon">▱</span><div><b>{name}</b><p>{body}</p><small>{ready?'Current data preview; generate to save a snapshot':'Report aggregation and orchestration pending'}</small></div><Status color={ready?'blue':'neutral'}>{ready?'Available':'Not connected'}</Status>{ready?<button className="filter" disabled={!target || busy} onClick={load}>{busy?'Loading…':'View'}</button>:<Future reason="Report workflow pending">View</Future>}<Future reason="Generate a company snapshot first">⇩</Future></div>)}</section>
    <Panel title="Saved during this session" eyebrow="REPORT SNAPSHOTS"><p className="panel-note">Previously saved reports remain in the backend. Historical listing needs a dashboard endpoint.</p>{generated.map(r=><div className="report-row" key={r.report_id}><span className="report-icon">▱</span><div><b>Report #{r.report_id} · {r.payload?.vendor?.display_name}</b><p>{date(r.created_at)} · {r.generated_by}</p></div><Status color="good">Saved</Status><button className="filter" onClick={()=>setPreview(r)}>View</button><button className="text-button" aria-label={'Download report '+r.report_id} onClick={()=>download('company-report-'+r.report_id+'.json',JSON.stringify(r,null,2))}>⇩</button></div>)}</Panel>
    <section className="report-callout"><div><span>▣</span><div><b>Reports preserve the evidence behind a decision.</b><p>Company snapshots include source freshness, review state, material events, and source references.</p></div></div><EmailReportButton vendorId={Number(target)} label="Email report →"/></section>
    {generator && <Modal title="Generate report snapshot" close={()=>{if(!busy)setGenerator(false);}}><form className="action-form" onSubmit={generate}><p>This creates a new immutable report using the saved backend assessment.</p><label>Generated by<input value={actor} onChange={e=>setActor(e.target.value)} maxLength={200} required disabled={busy}/></label><ErrorNotice error={error}/><button className="primary" disabled={busy || !actor.trim()}>{busy?'Saving…':'Generate snapshot'}</button></form></Modal>}
    {preview && <Modal wide title={preview.current?'Current report preview':'Report snapshot #'+preview.report_id} close={()=>setPreview(null)}><ReportView report={preview}/><div className="form-actions"><button className="filter" onClick={()=>download(preview.current?'current-report.json':'company-report-'+preview.report_id+'.json',JSON.stringify(preview,null,2))}>Download JSON</button><button className="filter" onClick={()=>window.print()}>Print / Save PDF</button><EmailReportButton vendorId={Number(target)}/></div></Modal>}
  </>;
}
export function ReportView({ report }) {
  const p = report.payload || {}, r = p.current_risk || {}, vendor = p.vendor || {};
  return <article className="report-document"><p className="eyebrow">{report.current?'LIVE PREVIEW · NOT AN IMMUTABLE SNAPSHOT':'IMMUTABLE SNAPSHOT'}</p><h2>{vendor.display_name || 'Company report'}</h2><Details rows={[[ 'Company number',vendor.company_number],['Generated',date(report.created_at || p.report_generated_at)],['Generated by',report.generated_by],['Report version',p.report_version],['Assessment',p.assessment_summary?.label || r.assessment_label],['Score',r.overall_score],['Grade',r.overall_grade],['Status',r.overall_status],['Confidence',r.data_confidence],['Trend',r.trend]]}/>
    <h3>Intake</h3><Details rows={Object.entries(vendor).map(([k,v])=>[label(k),v])}/>
    <h3>Risk dimensions</h3>{Object.entries(r.dimensions || {}).map(([key,d])=><div className="report-section" key={key}><b>{label(key)} · {label(d.state)} · Score {d.score ?? 'Unassessed'}</b><p>{d.summary}</p><small>Confidence: {label(d.confidence)}</small></div>)}
    <h3>Material events</h3>{(p.material_events||[]).length?p.material_events.map(e=><div className="report-section" key={e.event_id}><b>{e.title}</b><p>{e.description}</p><small>{date(e.detected_at)} · {label(e.severity)} · {label(e.confidence)}</small>{e.caution && <p className="evidence-note">{e.caution}</p>}<SourceLink url={e.source_url}/>{e.review && <p>Review: {label(e.review.decision)} · {e.review.reviewer} · {e.review.note}</p>}</div>):<p>No material events returned.</p>}
    <h3>Open alerts</h3>{(p.open_alerts||[]).map(a=><div className="report-section" key={a.alert_id}><b>{a.title} · {label(a.severity)}</b><p>{a.reason}</p><small>{label(a.status)} · Owner: {a.assigned_to || 'Unassigned'} · Due {date(a.sla_due_at)}</small></div>)}
    <h3>Sources & freshness</h3><SourceRows rows={p.data_freshness}/><h3>Financial evidence</h3><p>{p.financial_review?.label || 'Review status unavailable'} · {(p.financial_filing_evidence||[]).length} captured pages. Extracted financial figures are not displayed.</p>
    <h3>Recommended review areas</h3><ul>{(p.recommended_review_areas||[]).map(item=><li key={item}>{item}</li>)}</ul><p className="report-disclaimer">{p.disclaimer}</p>
  </article>;
}
export function Operations({ store }) {
  const rows = sourceRows(store.companies), jobs = store.audit.filter(a=>/refresh_all|job|notification|escalat/.test(a.action));
  return <><PageTitle eyebrow="SYSTEM OVERSIGHT" title="Operations" description="Inspect available source checks, audit activity, and notification delivery."><button className="filter" disabled={store.loading || store.enriching} onClick={store.reload}>↻ Check health</button></PageTitle>
    <div className="layout-two"><Panel title="Source coverage" eyebrow="SOURCE STATUS"><SourceRows rows={rows}/><div className="source-row"><span className="source-icon neutral">◌</span><div><b>External intelligence</b><small>Provider configuration pending</small></div></div></Panel><Panel title="Automation history" eyebrow="RECENT JOBS"><p className="panel-note">Activity below comes from the latest 100 audit entries. Full job and lock status needs a dashboard endpoint.</p>{jobs.length?jobs.map(j=><div className="job-row" key={j.id}><span>◌</span><div><b>{label(j.action)}</b><small>{text(j.details)}</small></div><small>{date(j.created_at)}</small></div>):<Empty title="No automation activity returned">This does not confirm that scheduled jobs are running.</Empty>}</Panel></div>
    <Panel title="Notification delivery" eyebrow="ALERT CHANNELS"><p className="panel-note">Delivery states are reported by the backend; sending email remains the responsibility of the n8n workflow.</p>{store.alerts.length?store.alerts.map(a=><div className="job-row" key={a.alert_id}><Status value={a.notification_state}/><div><b>{a.title}</b><small>{a.notification_count ?? 0} attempts · {a.notification_last_error || 'No recorded delivery error'}</small></div><small>{date(a.last_notified_at)}</small></div>):<Empty title="No alert deliveries to display"/>}</Panel>
  </>;
}
